###
//Добавление пользователя
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Рандом",
  "login": "random",
  "password": "11111",
  "email": "random@gmail.com"
}

###
//Попытка добавления пользователя с незаполненными полями
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Рандом",
  "password": "11111"
}

###
//Вывод пользователя с его корзиной
GET localhost:8080/users/3
Content-Type: application/json

###
//Попытка вывести несуществующего пользователя
GET localhost:8080/users/11
Content-Type: application/json

###
//Удаление пользователя
DELETE localhost:8080/users/7

###
//Попытка удалить несуществующего пользователя
DELETE localhost:8080/users/33

###
GET localhost:8080/users
Content-Type: application/json

{
  "login": "No211",
  "password": "12345"
}

###
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "No211",
  "email": "No211@gmail.com",
  "password": "123456"
}