###
//Добавление товара
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Мохито",
  "price": 350,
  "amount": 10
}

###
//Попытка добавления товара с незаполненными полями
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Мохито",
  "amount": 10
}

###
//Обновление товара
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 6,
  "name": "Капуста",
  "price": 95,
  "amount": 10
}

###
//Попытка обновления товара с незаполненными полями
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 6,
  "name": "Капуста",
  "price": 95
}

###
//Удаление товара
DELETE localhost:8080/products/9

//Попытка удаления товара, который находится в корзине одного или нескольких пользователей
###
DELETE localhost:8080/products/1

###
//Попытка удаления несуществующего товара
DELETE localhost:8080/products/111

###
//Получение товара
GET localhost:8080/products/4

###
//Попытка получения несуществующего товара
GET localhost:8080/products/444

###
//Получение товара по имени
GET localhost:8080/products?name=Кофе
Content-Type: application/json

###
//Получение товара по части имени
GET localhost:8080/products?name=Ко
Content-Type: application/json

###
//Получение списка всех товаров
GET localhost:8080/products
Content-Type: application/json