###
POST localhost:8080/clients
Content-Type: application/json

{
  "name": "Unanimous",
  "login": "admin",
  "password": "admin",
  "email": "ad.Unanimous@Unanim.ad"
}

###
GET localhost:8080/clients/get/459830

###
DELETE localhost:8080/clients/delete/245984



###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Яблоки",
  "price": 100,
  "amount": 10
}

###
GET localhost:8080/products/all

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 817969,
  "name": "Банан",
  "price": 80,
  "amount": 8
}

###
DELETE localhost:8080/products/delete/817969

###
GET localhost:8080/products/name/Яблоки



###
POST localhost:8080/baskets/add/418764/1

###

###
PUT localhost:8080/baskets
Content-Type: application/json

{
  "id": 418764,
  "amount": 2000
}

###
POST localhost:8080/baskets/delete/105424



###
POST localhost:8080/payment/pay/445273
Content-Type: application/json

{
  "idClient": 459830,
  "sum": 2000000000
}