###
POST localhost:8080/clients
Content-Type: application/json

{
  "name": "Unanimous",
  "login": "admin",
  "password": "admin",
  "email": "ad.Unanimous@Unanim.ad",
  "card": 1111
}

###
GET localhost:8080/clients/get/6

###
DELETE localhost:8080/clients/delete/6



###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Яблоки",
  "price": 102
}

###
GET localhost:8080/products/name/Яблоки

###
GET localhost:8080/products/all

###
GET localhost:8080/products/id/2

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 1,
  "name": "Банан",
  "price": 800
}

###
DELETE localhost:8080/products/delete/2





###
POST localhost:8080/baskets/add/2/1/2

###
PUT localhost:8080/baskets/2
Content-Type: application/json

{
  "id": 1,
  "price": 1
}

###
POST localhost:8080/baskets/delete/2/1



###
POST localhost:8080/payment
Content-Type: application/json

{
  "idClient": 2
}