###
POST localhost:8080/clients
Content-Type: application/json

{
  "name": "Unanimous",
  "login": "admin",
  "password": "admin",
  "email": "ad.Unanimous@Unanim.ad",
  "card": 1111
}

###
GET localhost:8080/clients?id=2

###
DELETE localhost:8080/clients?id=6



###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "sdfsdf",
  "price": 12
}

###
GET localhost:8080/products?name=Яблоки

###
GET localhost:8080/products

###
GET localhost:8080/products/?id=2

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 2,
  "name": "Банан",
  "price": 800
}

###
DELETE localhost:8080/products?id=2





###
POST localhost:8080/baskets?idClient=2
Content-Type: application/json

{
  "idProduct": 100,
  "count": 1
}

###
PUT localhost:8080/baskets?idClient=2
Content-Type: application/json

{
  "id": 100,
  "count": 1
}

###
DELETE localhost:8080/baskets?idClient=2&idProduct=1



###
POST localhost:8080/payment
Content-Type: application/json

{
  "idClient": 3
}